#!/bin/bash
# LaTeX - you might consider installing texlive-full instead...
sudo apt install -y texlive texlive-pictures texlive-lang-german texlive-lang-english texlive-science texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra biber